const projectList = [
    {
        id: 1,
        title: 'Mobile Medical App',
        description: 'Description for project one',
        imagesDir: 'src/assets/mma',
        images: [
            'landingPage.png',
            'login.png',
            'createAccount.png',
            'home.png',
            'drawer.png',
            'form.png',
            'patientSearch.png',
            'schedule.png',
        ],
        stack: [
            'React Native',
            'Node.js',
            'Supabase',
            'Expo',
            'JavaScript',
            'TypeScript',
        ],
        files: 'https://github.com/DreamTeam131/Medical-App',
    },
    {
        id: 2,
        title: 'Sun Armor Ai',
        description: 'Description for project two',
        imagesDir: 'src/assets/sa',
        images: ['home.jpg'],
        stack: [
            'React',
            'Node.js',
            'Vite',
            'PyTorch',
            'TensorFlow',
            'JavaScript',
            'Python',
        ],
        link: 'https://wsc0tt.github.io/SunArmorAi/',
        files: 'https://github.com/wsc0tt/SunArmorAi',
    },
    {
        id: 3,
        title: 'Maritime Assign',
        description: 'Description for project three',
        imagesDir: '/assets/ma',
        images: [],
        stack: ['React', 'Node.js', 'Vite', 'Docker', 'Supabase', 'JavaScript'],
    },
    {
        id: 4,
        title: 'OpenGL Game of Life',
        description: 'Description for project four',
        imagesDir: '/assets/gol',
        images: ['gameOfLife.png'],
        stack: ['Java', 'OpenGL', 'Swing'],
    },
    {
        id: 5,
        title: 'Other Projects',
        description: 'Description for project five',
        stack: ['Various Technologies'],
    },
]

export default projectList
