const projectList = [
    {
        id: 3,
        title: 'Maritime Assign',
        description:
            'Maritime Assign is a web-based job management platform built for the Marine Engineers’ Beneficial Association (MEBA) to replace their outdated Google Sheets-based job board. The application centralizes job listings, streamlines dispatch workflows, and provides secure role-based access for union members, dispatchers, and administrators. It was created to improve reliability, security, efficiency, and real-time visibility for a nationwide maritime job distribution system.',
        imagesDir: 'ma',
        images: [
            'login.png',
            'forgot.png',
            'dash.png',
            'manage.png',
            'add.png',
            'board.png',
            'users.png',
        ],
        stack: [
            'React',
            'Node.js',
            'Vite',
            'Docker',
            'Supabase',
            'JavaScript',
            'PostgreSQL',
            'TailwindCSS',
            'React Testing Library',
            'Jest',
            'Vitest',
            'Formik',
            'Cloudflare',
        ],
        github: 'https://github.com/Maritime-Assign/MEBA',
        link: 'https://meba.pages.dev/',
        video: 'https://www.youtube.com/embed/scoow5AcclU?si=BNqhlPdddotEk7Lm',
    },
    {
        id: 2,
        title: 'Sun Armor Ai',
        description:
            'A web app that uses convolutional neural networks to classify skin lesions from uploaded images. Trained on dermatology datasets using PyTorch and TensorFlow, with client-side inference for fast results. Built with React and TypeScript, and published open-source for developers and researchers.',
        imagesDir: 'sa',
        images: ['home.jpg', 'analysis.png'],
        stack: [
            'React',
            'Node.js',
            'Vite',
            'PyTorch',
            'TensorFlow',
            'JavaScript',
            'Python',
            'ONNX',
            'Tensorflow.js',
            'HuggingFace',
        ],
        link: 'https://wsc0tt.github.io/SunArmorAi/',
        github: 'https://github.com/wsc0tt/SunArmorAi',
    },
    {
        id: 1,
        title: 'Mobile Medical App',
        description:
            'This project was my first exposure to Full-stack and mobile development, where I led a team of 6 other computer science students in creating a real product for a medical organization.' +
            'The project was completed in 6 2-week sprints, working with evolving client requirements and feature requests. ',

        imagesDir: 'mma',
        images: [
            'landingPage.png',
            'login.png',
            'createAccount.png',
            'home.png',
            'drawer.png',
            'form.png',
            'patientSearch.png',
            'schedule.png',
        ],
        stack: [
            'React Native',
            'Node.js',
            'Supabase',
            'Expo',
            'JavaScript',
            'TypeScript',
        ],
        github: 'https://github.com/DreamTeam131/Medical-App',
    },
    {
        id: 4,
        title: 'OpenGL Game of Life',
        description: 'Description for project four',
        imagesDir: 'gol',
        images: ['gameOfLife.png'],
        stack: ['Java', 'OpenGL', 'Swing', 'LWJGL', 'GLSL'],
        github: 'https://github.com/wsc0tt/GameOfLife',
    },
]

export default projectList
